const path = require('path')
const dirPath = path.join(__dirname, '/text.txt')
const fs = require('fs')
const readableStream = fs.createReadStream(dirPath, 'utf-8')
readableStream.on('data', (chunk) => console.log(chunk))
